### ISSUE TITLE
Log4J vulnerable

### ISSUE THREAD

**Issue by Unixware** [KodeMunkie/imagetozxspec#6]
FYI from my checks :  imagetozxspec-2.2.1.jar contains Log4J-1.x AND Log4J-2.x _CRAZY_   >= 2.10.0 _VULNERABLE_

thanks

**Comment by KodeMunkie** [comment]
TBF this is a standalone app that's not a service or internet hosted so has no real risk. Log4j 2 is used by code I've written, if there's another, it'll be used by a dependency. I've already merged in one dependabot fix to main, will do the other later. As such I'm not putting out a new release however you're welcome to build from main :)

**Comment by Unixware** [comment]
thanks, just in anycase... I did a scan on all of my java apps..
