### ISSUE TITLE
[Windows] v2.2.2 Gives error when running

### ISSUE THREAD

**Issue by zzedmore** [KodeMunkie/imagetozxspec#9]
Hi, the latest Windows version (2.2.2) doesn't seem to run. It gives a Java error -

![CpWz_003](https://user-images.githubusercontent.com/79696530/185084478-dc196fb8-86f5-409b-b401-3ee9da8563bb.png)

An older version, 2.0.2 works fine.

I'm using Windows 10 64bit and Java Version 8 Update 341.

EDIT - v2.2.1 works, but doesn't output .tap slideshow (ticked in options). I've selected the output directory but nothing appears. It seems only v2.0.2 works fully.

**Comment by KodeMunkie** [comment]
2.2.2 is Java 17 or above. It won't run on Java 8.

**Comment by zzedmore** [comment]
Well thanks for letting me know over a year later ! Your readme installation instructions point to version 8 of Java.

**Comment by KodeMunkie** [comment]
> Well thanks for letting me know over a year later ! Your readme installation instructions point to version 8 of Java.

No they don't. They directly point to the latest version of Java to download and version 2.2.2 release notes specifically mention Java 17.
Thanks for reporting.
